{
 "title": "Quorum Store",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"}, chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"}, cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"}, kubernetes_pod_name)"
    }
   },
   { "name": "role", "query": { "query": "label_values(role)" } },
   {
    "name": "interval",
    "label": "Aggregation Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Batch Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NUM_TXN_PER_BATCH",
   "type": "timeseries",
   "description": "Histogram for the number of transactions per batch.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(quorum_store_num_txn_per_batch_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_num_txn_per_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUM_FRAGMENT_PER_BATCH",
   "type": "timeseries",
   "description": "Histogram for the number of fragments per batch.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "rate(quorum_store_num_fragment_per_batch_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_num_fragment_per_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUM_BATCH_PER_BLOCK",
   "type": "timeseries",
   "description": "Histogram for the number of batches per (committed) blocks.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(quorum_store_num_batch_per_block_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_num_batch_per_block_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUM_TXNS_PER_BLOCK",
   "type": "timeseries",
   "description": "Histogram for the number of txns per (committed) blocks.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_num_txns_per_block_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(aptos_consensus_num_txns_per_block_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Batch and Proof Creation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "PULLED_TXNS_NUM",
   "type": "timeseries",
   "description": "Histogram for the number of txns are pulled.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_pulled_txns_num_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_pulled_txns_num_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PULLED_TXNS_COUNT",
   "type": "timeseries",
   "description": "Count of the pulled txns.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_pulled_txn_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PULLED_EMPTY_TXNS_COUNT",
   "type": "timeseries",
   "description": "Count of the pulled empty txns.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "rate(quorum_store_pulled_empty_txn_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created batches since last restart.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(quorum_store_created_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATED_EMPTY_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created empty batches since last restart.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(quorum_store_created_empty_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}-{{role}}"
    }
   ]
  },
  {
   "title": "GET_BATCH_FROM_DB_COUNT",
   "type": "timeseries",
   "description": "Count of the number of get batch request from QS DB.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "rate(quorum_store_get_batch_from_db_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELIVERED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the created batches since last restart.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(quorum_store_delivered_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELIVERED_FRAGMENTS_COUNT",
   "type": "timeseries",
   "description": "Count of the delivered fragments since last restart.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "rate(quorum_store_delivered_fragments_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELIVERED_END_BATCH_COUNT",
   "type": "timeseries",
   "description": "Count of the delivered end batch since last restart.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "rate(quorum_store_delivered_end_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LOCAL_POS_COUNT",
   "type": "timeseries",
   "description": "Count of the created proof-of-store (PoS) since last restart.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "rate(quorum_store_local_PoS_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REMOTE_POS_COUNT",
   "type": "timeseries",
   "description": "Count of the received PoS since last restart.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "rate(quorum_store_remote_PoS_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TIMEOUT_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the timeout batches at the sender side.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "rate(quorum_store_timeout_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MISSED_BATCHES_COUNT",
   "type": "timeseries",
   "description": "Count of the missed batches when execute.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "rate(quorum_store_missed_batch_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "new batch: creating POS success rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "rate(quorum_store_batch_successful_creation_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_batch_successful_creation_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "batch collected num votes % (eventually) ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "(rate(quorum_store_batch_received_replies_votes_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_batch_received_replies_votes_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])) / aptos_consensus_current_epoch_validators{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "batch collected voting power % (eventually)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "(rate(quorum_store_batch_received_replies_voting_power_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_batch_received_replies_voting_power_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) ) / aptos_total_voting_power{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Backpressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "QS_BACKPRESSURE_TXN_COUNT",
   "type": "timeseries",
   "description": "Indicator of whether Quorum Store is backpressured. QS should be backpressured when (1) number of batches exceeds the threshold, or (2) consensus is backpressured.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(quorum_store_backpressure_txn_count_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_backpressure_txn_count_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QS_BACKPRESSURE_PROOF_COUNT",
   "type": "timeseries",
   "description": "Indicator of whether Quorum Store is backpressured. QS should be backpressured when (1) number of batches exceeds the threshold, or (2) consensus is backpressured.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
   "targets": [
    {
     "expr": "rate(quorum_store_backpressure_proof_count_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_backpressure_proof_count_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QS_BACKPRESSURE_DYNAMIC_MAX",
   "type": "timeseries",
   "description": "placeholder",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "rate(quorum_store_backpressure_dynamic_max_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_backpressure_dynamic_max_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BLOCK_BYTES_WHEN_PULL",
   "type": "timeseries",
   "description": "Histogram for the total size of transactions per block when pulled for consensus.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "expr": "rate(quorum_store_block_bytes_when_pull_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_block_bytes_when_pull_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUM_TOTAL_TXNS_LEFT_ON_COMMIT",
   "type": "timeseries",
   "description": "Histogram for the number of locally created batches/PoS left when forming a block proposal.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "rate(quorum_store_num_total_txns_left_on_commit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_num_total_txns_left_on_commit_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NUM_TOTAL_PROOFS_LEFT_ON_COMMIT",
   "type": "timeseries",
   "description": "Histogram for the number of locally created batches/PoS left when forming a block proposal.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 52 },
   "targets": [
    {
     "expr": "rate(quorum_store_num_total_proofs_left_on_commit_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_num_total_proofs_left_on_commit_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PROOF_SIZE_WHEN_PULL",
   "type": "timeseries",
   "description": "Histogram for the number of proof-of-store per block when pulled for consensus.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "rate(quorum_store_proof_size_when_pull_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_proof_size_when_pull_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BLOCK_SIZE_WHEN_PULL",
   "type": "timeseries",
   "description": "Histogram for the number of transactions per block when pulled for consensus.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 52 },
   "targets": [
    {
     "expr": "rate(quorum_store_block_size_when_pull_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_block_size_when_pull_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Batch Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "SENT_BATCH_REQUEST_COUNT",
   "type": "timeseries",
   "description": "Count of the number of batch request sent to other nodes.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(quorum_store_sent_batch_request_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SENT_BATCH_REQUEST_RETRY_COUNT",
   "type": "timeseries",
   "description": "Count of the number of batch request retry sent to other nodes.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 60 },
   "targets": [
    {
     "expr": "rate(quorum_store_sent_batch_request_retry_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RECEIVED_BATCH_REQUEST_COUNT",
   "type": "timeseries",
   "description": "Count of the number of batch request received from other nodes.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "rate(quorum_store_received_batch_request_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RECEIVED_BATCH_REQUEST_TIMTOUT_COUNT",
   "type": "timeseries",
   "description": "Count of the number of batch request received from other nodes that is timeout.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 60 },
   "targets": [
    {
     "expr": "rate(quorum_store_received_batch_request_timeout_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "BATCH_CREATION_DURATION",
   "type": "timeseries",
   "description": "Histogram of the time durations for batch creation.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "rate(quorum_store_batch_creation_duration_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_batch_creation_duration_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EMPTY_BATCH_CREATION_DURATION",
   "type": "timeseries",
   "description": "Histogram of the time durations for empty batch creation.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "targets": [
    {
     "expr": "rate(quorum_store_empty_batch_creation_duration_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_empty_batch_creation_duration_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BATCH_TO_POS_DURATION",
   "type": "timeseries",
   "description": "Histogram of the time durations from batch creation to PoS creation.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "targets": [
    {
     "expr": "rate(quorum_store_batch_to_PoS_duration_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_batch_to_PoS_duration_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "CONSENSUS_CHANNEL_MSGS",
   "type": "timeseries",
   "description": "Counters(queued, dequeued, dropped) related to consensus channel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_channel_msgs_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QUORUM_STORE_CHANNEL_MSGS",
   "type": "timeseries",
   "description": "Counters(queued, dequeued, dropped) related to quorum store channel",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "targets": [
    {
     "expr": "rate(aptos_quorum_store_channel_msgs_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "BLOCK_RETRIEVAL_CHANNEL_MSGS",
   "type": "timeseries",
   "description": "Counters(queued, dequeued, dropped) related to block retrieval channel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_block_retrieval_channel_msgs_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Message Sent",
   "type": "timeseries",
   "description": "The number of messages sent group by types",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_sent_msgs_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Message Received",
   "type": "timeseries",
   "description": "The number of messages received group by types",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "targets": [
    {
     "expr": "rate(aptos_consensus_received_msgs_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Batch Expiration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "EXPIRED_PROOFS_WHEN_PULL",
   "type": "timeseries",
   "description": "Histogram for the number of expired proof-of-store when pulled for consensus.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "rate(quorum_store_expired_proof_size_when_pull_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_proof_size_when_pull_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GAP_BETWEEN_BATCH_EXPIRATION_AND_CURRENT_TIME_WHEN_SAVE",
   "type": "timeseries",
   "description": "Histogram for the gaps between expiration round of the batch and the last certified round, and expiration round is higher.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 95 },
   "targets": [
    {
     "expr": "rate(quorum_store_gap_batch_expiration_and_current_time_when_save_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_gap_batch_expiration_and_current_time_when_save_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GAP_BETWEEN_BATCH_EXPIRATION_AND_CURRENT_TIME_WHEN_PULL_PROOFS",
   "type": "timeseries",
   "description": "Histogram for the gaps between expiration round and the current round when pulling the proofs, and expiration round is lower.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 95 },
   "targets": [
    {
     "expr": "rate(quorum_store_gap_batch_expiration_and_current_round_when_pull_sum{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval]) / rate(quorum_store_gap_batch_expiration_and_current_round_when_pull_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 } },
  {
   "title": "EXPIRED_BATCH_FRAGMENTS_COUNT",
   "type": "timeseries",
   "description": "Count of the expired batch fragments at the receiver side.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "rate(quorum_store_expired_batch_fragments_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MISSED_BATCH_FRAGMENTS_COUNT",
   "type": "timeseries",
   "description": "Count of the missed batch fragments at the receiver side.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 103 },
   "targets": [
    {
     "expr": "rate(quorum_store_missed_batch_fragments_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EXCEEDED_STORAGE_QUOTA_COUNT",
   "type": "timeseries",
   "description": "Count of the exceeded storage quota.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 103 },
   "targets": [
    {
     "expr": "rate(quorum_store_exceeded_storage_quota_count{chain_name=~\"$chain_name\", cluster=~\"$cluster\", metrics_source=~\"$metrics_source\", namespace=~\"$namespace\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}